repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
    -   id: pip-compile
        name: pip-compile requirements.dev.in
        stages: [manual]
        args: [requirements.dev.in]
        files: ^requirements(.dev)?\.(in|txt)$
    -   id: pip-compile
        name: pip-compile requirements.in
        stages: [manual]
        args: [requirements.in]
        files: ^requirements\.(in|txt)$
