[tool.mypy]
mypy_path = 'stubs'

[[tool.mypy.overrides]]
module = [
    'discord.*',
    'PIL',
]
ignore_missing_imports = true
disable_error_code = [
    'method-assign',
]

[tool.pycodestyle]
ignore = [
    'D100',
    'D103',
]
